apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ollive.labels" . | nindent 4 }}
data:
  APP_ENV: "prod"
  LOG_LEVEL: "INFO"
  DATABASE_URL: {{ include "ollive.databaseUrl" . | quote }}
  REDIS_URL: {{ include "ollive.redisUrl" . | quote }}
  CLICKHOUSE_HOST: {{ include "ollive.clickhouseHost" . | quote }}
  CLICKHOUSE_PORT: {{ .Values.clickhouse.httpPort | quote }}
  CLICKHOUSE_DB: "ollivelogs"
  EVENT_BUS_STREAM: "logs.raw"
  EVENT_BUS_DLQ: "logs.dlq"
  EVENT_BUS_CONSUMER_GROUP: "cg-store"
  OLLIVE_INGEST_URL: "http://{{ .Release.Name }}-ingest-api.{{ .Values.global.namespace }}.svc.cluster.local:{{ .Values.ingestApi.port }}/v1/logs"
  DEFAULT_PROVIDER: {{ .Values.config.defaultProvider | quote }}
  DEFAULT_MODEL: {{ .Values.config.defaultModel | quote }}
  PII_REDACTION_ENABLED: {{ .Values.config.piiRedactionEnabled | quote }}
  STORE_RAW: {{ .Values.config.storeRaw | quote }}
  RATE_LIMIT_PER_MIN: {{ .Values.config.rateLimitPerMin | quote }}
  RATE_LIMIT_TOKENS_PER_MIN: {{ .Values.config.rateLimitTokensPerMin | quote }}
  CHAT_CONTEXT_TURNS: {{ .Values.config.chatContextTurns | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ include "ollive.otlpEndpoint" . | quote }}
  OTEL_SERVICE_NAMESPACE: "ollivelogs"
