global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    cluster: ollivelogs-local

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: chat-api
    metrics_path: /metrics
    static_configs:
      - targets: ["chat-api:8001"]
        labels:
          service: chat-api

  - job_name: ingest-api
    metrics_path: /metrics
    static_configs:
      - targets: ["ingest-api:8002"]
        labels:
          service: ingest-api

  - job_name: log-consumer
    metrics_path: /metrics
    static_configs:
      - targets: ["log-consumer:8003"]
        labels:
          service: log-consumer

  - job_name: otel-collector
    metrics_path: /metrics
    static_configs:
      - targets: ["otel-collector:8889"]
        labels:
          service: otel-collector
